name:                dead
version:             0.1.0.0
github:              "githubuser/dead"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dead#readme>

dependencies:
- base >= 4.7 && < 5
- language-c == 0.9.1
- mtl == 2.2.2
- pretty-simple == 4.1.0.0
- containers == 0.6.5.1 
- Stack == 0.4.0
- text == 1.2.5.0
- MonadRandom == 0.5.3
- random == 1.2.1
- lens == 5.0.1
- prettyprinter == 1.7.1

library:
  source-dirs: src

executables:
  dead-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - dead

tests:
  dead-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dead
